### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by slackr31337** [dwhall/sx127x_ahsm#1]
Is there a script that is missing?

root@raspberrypi:/opt/sx127x_ahsm# python3 ./setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/sx127x_ahsm
copying sx127x_ahsm/mock_spidev.py -> build/lib/sx127x_ahsm
copying sx127x_ahsm/phy_sx127x_ahsm.py -> build/lib/sx127x_ahsm
copying sx127x_ahsm/phy_sx127x_stngs.py -> build/lib/sx127x_ahsm
copying sx127x_ahsm/phy_sx127x_spi.py -> build/lib/sx127x_ahsm
copying sx127x_ahsm/phy_gpio_ahsm.py -> build/lib/sx127x_ahsm
copying sx127x_ahsm/mock_gpio.py -> build/lib/sx127x_ahsm
copying sx127x_ahsm/__init__.py -> build/lib/sx127x_ahsm
running build_scripts
creating build/scripts-3.7
error: file '/opt/sx127x_ahsm/scripts/heymac_gen_identity.py' does not exist

**Comment by dwhall** [comment]
Thanks for the feedback.

I hope you read the last paragraph of the README.
sx127x_ahsm is meant to be used as a submodule.
This means this submodule doesn’t do much on its own and “python setup.py install” is not recommended.

To address your error message:
The setup.py is out-of-date.
You can get going by removing line 16 in setup.py
I will make the same edit and push by the end of the day.

!!Dean
